import React from 'react';
import MyMenu from '@/components/molecules/myMenu/myMenu'

import MyFooter from '@/components/molecules/myFooter/myFooter';

import './globals.css'

import '@/app/globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <div className='container'>
          <MyMenu />
          {children}
          <MyFooter />
        </div>
      </body>
    </html>
  );
}
