import MyMenu from '@/components/molecules/myMenu/myMenu'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <MyMenu />   
      <div>{children}</div>
              
      </body>
    </html>
  )
}
